config/routes.rb
Rails.application.routes.draw do
  devise_for :users , path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'password', 
            confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'singup' },
            :controllers => {:registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks"}
  
  devise_scope :user do
    authenticated :user do
      root 'pages#home'
    end

    unauthenticated do
      root 'pages#landing', as: :unauthenticated_root
    end
  end

  get '/home'                   => 'pages#home'
  get '/edit_profile'           => 'users#edit'
  get '/beneficiaries'          => 'person_dependents#beneficiary'
  post '/dependent_destroy/:id' => 'person_dependents#destroy'
  post '/finance_data'          => 'persons#finance_data'
  get '/transaction/create'     => 'transactions#new'
  post '/transaction/create'    => 'transactions#create'
  
  resources :persons
  post '/users/password' => 'users#password'

end

app/views/shared/_auth.html.erb
<% if !current_user.present? %>
	<div class='max-height' id="landing-auth-container" style="display:none;">
		<%= render 'shared/loader' %>
    <div class="container-opacity">
      <%= render :template => 'devise/sessions/new' %>
    </div>
    <button type="button" class="boxclose opened" onClick="return box_close($(this));"></button>
  </div>
<% end %>

app/views/shared/_loader.html.erb
<div id="submit-loader" class="not-display">
  <div id="loading-img" >
    <img id="loader-gif" style="width: 100px;" src="<%= image_path('ajax-loader.gif') %>"/>
  </div>
</div>

app/views/shared/_messages.html.erb
<script type="text/javascript">
	<% flash.each do |name, msg| %>
		$.notify({
			// options
			message: "<%= msg %>" 
		},{
			// settings
			placement: {
				from: "bottom",
				align: "center"
			},
			// Devise uses notice instead of info
			<% if name == "notice" or name == "info" %>
				icon: 'glyphicon glyphicon-info-sign',
				type: 'info'
			<% elsif name == "warning" %>
				icon: 'glyphicon glyphicon-warning-sign',
				type: 'warning'
			<% elsif name == "danger" %>
				icon: 'glyphicon glyphicon-exclamation-sign',
				type: 'danger'
			<% elsif name == "success" %>
				icon: 'glyphicon glyphicon-check',
				type: 'success'
			<% end %>
		});
	<% end %>
</script>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
	<div class="navbar-header">
	  <div class="inline" style="margin-top:10px;">
	    <%= link_to 'Learn Easy', root_path, :class => 'no-link header-nav', :style => 'padding:10px;' %>
	  </div>
	  <% if user_signed_in? %>
	  <button type="button" class="pull-right item-mobile" id="mostrar-nav" 
      style="background-color: transparent; margin-right: 10px; margin-top: 8px; border: none;" >
      <i class="fa fa-bars fa-2x"></i>
    </button>
    <% end %>
	</div>

	<% if user_signed_in? %>
    <% person = current_user.person %>
    <ul class="nav navbar-nav navbar-right item-page">
      <li class="nav-pic">
        <%= link_to edit_profile_path do %>
          <%= person.profile_picture( { size: 28 } ) %>
        <% end %>
      </li>

      <li class="dropdown item-page" style="margin-left:7px;">
        <button class="dropdown-toggle nav-user" id="drop-link" type="button" data-toggle="dropdown">
        <%= person.short_name %> <span class="caret"></span></button>
        <ul class="dropdown-menu" id="drop-toggle">
          <li>
            <%= link_to edit_profile_path, :class => 'padding-v6' do %>
              <%= person.profile_picture( { size: 38, klass: 'img-circle drop-img'} ) %>
              <%= person.full_name %>
              <div class="font-11 gray">Ver Perfil</div>
            <% end %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to destroy_user_session_path, :method => :delete do %>
            <span class="fa fa-sign-out menu-icono-title"></span> Finalizar Sessión
            <% end %>
          </li> 
        </ul>
      </li>    

    </ul> 
  <% else %>
    <ul class="nav navbar-nav navbar-right">
      <button type="button" class="btn circle-button b-green" id="landing-launch-auth" 
        onClick="return auth_show();" style="margin-right: 20px; margin-top: 7px;">
              Registrate / inicia sesión</button>
    </ul>
  <% end %>
</nav>

app/views/shared/_sidebar.html.erb
<nav class="nav-mobile">
	<ul class="menu">
		
	  <% if user_signed_in? %>
	    <% person = current_user.person %>
			<li class="dropdown list" id="user-li">
				<a href="#" class="dropdown-toggle" id="user-menu">
          <%= person.profile_picture( { size: 34, klass: 'img-circle'} ) %>
          <div class="menu-label not-display"><%= person.full_name %></div>
	      </a>
			  <ul class="submenu">
			    <li><%= link_to('Edit Profile', edit_profile_path ) %></li>
			    <li><%= link_to('Logout', destroy_user_session_path, :method => :delete ) %></li>                
			  </ul>		  
			</li>
	  <% end %>
		
		<li id="stock-li">
			<%= link_to '/home' do %>
			<i class="fa fa-h-square"  id="menu-icono-title"></i>
			<div class="menu-label not-display"> Home</div></a>
			<% end %>
		</li>
		
		<li id="caja-li">
			<a href="/beneficiaries" ><i class="fa fa-file-text-o" id="menu-icono-title"></i>
			<div class="menu-label not-display"> Beneficiarios</div></a>
		</li>

		<li id="record-li">
			<a href="/transaction/create" ><i class="fa fa-pencil-square-o" id="menu-icono-title"></i>
			<div class="menu-label not-display"> Generar flujo</div></a>
		</li>

		<li id="record-li">
			<a href="#" ><i class="fa fa-pie-chart" id="menu-icono-title"></i>
			<div class="menu-label not-display"> Reportes</div></a>
		</li>
		
	</ul>  
</nav>
<script type="text/javascript">
	$('#mostrar-nav').on('click',function(){
		show_menu();
  });
  $( ".nav-mobile" )
  .mouseenter(function() {
  	$('nav.nav-mobile').addClass('mostrar');
  	setTimeout(function(){ $('.menu-label').removeClass('not-display'); }, 100);
  })
  .mouseleave(function() {
    $('nav.nav-mobile').removeClass('mostrar');
  	setTimeout(function(){ 
  	  $('.menu-label').addClass('not-display'); 
  	  $('.dropdown.list').removeClass('nohover');
  	}, 100);
  });
  function show_menu(){
   	$('nav.nav-mobile').toggleClass('mostrar');
  	setTimeout(function(){ $('.menu-label').toggleClass('not-display'); }, 100);
  }
  $(document).ready(function(){
	  $('.dropdown.list').on('click',function(){
	    var actual = $(this);
	    $('.dropdown.list').each(function(){
	      if($(this)[0] != actual[0] ){
	          $(this).removeClass('nohover');
	      }
	    });
	    actual.toggleClass('nohover');
	  });
	});
</script>

<% if @view.present? %>
	<script type="text/javascript">
		$('<%= @view %>').addClass('actives');
	</script>
<% end %>